# Predict Glassdoor Reviews
Use trained model to predict sentiment of Glassdoor Reviews.

In [4]:
# @title Environment running
running_local = True  # @param {type:"boolean"}
if running_local:
    running_colab = running_kaggle = False
else:
    running_colab = False  # @param {type:"boolean"}
    running_kaggle = True  # @param {type:"boolean"}

In [5]:
if running_colab:
    from google.colab import drive

    drive.mount("/content/drive")

## Loading the model

In [7]:
import logging
import numpy as np
import pandas as pd
import platform
import random
import torch
import torch.nn as nn

from tqdm import tqdm
from transformers import BertTokenizer, BertModel

WARNING:tensorflow:From c:\venvs\venv_sent_analysis\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [8]:
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.FileHandler("predict_metrics.log"), logging.StreamHandler()],
)

In [ ]:
RANDOM_SEED = 103
BERTIMBAU_PATH = "neuralmind/bert-base-portuguese-cased"
BERTIMBAU_HIDDEN_SIZE = 768
TOKEN_MAX_LENGTH = 512
N_CLASSES = 3

PREDICTIONS_PATH = "."
VALIDATION_DATASET_NAME = 'validation_glassdoor_reviews.csv'
GOLDEN_DATASET_NAME = ".csv"

In [10]:
torch.manual_seed(RANDOM_SEED)

In [11]:
random.seed(RANDOM_SEED)

In [12]:
np.random.seed(RANDOM_SEED)

In [13]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"There are {torch.cuda.device_count()} GPU(s) available.")
    print("Device name:", torch.cuda.get_device_name(0))
else:
    print("No GPU available, using the CPU instead.")
    device = torch.device("cpu")

There are 1 GPU(s) available.
Device name: NVIDIA GeForce GTX 1650

In [16]:
if running_colab:
    dataset = pd.read_csv(
        f"/content/drive/MyDrive/UFMT/Gestão e Ciência de Dados/Disciplinas/14 - Seminário e Metodologia da Pesquisa/Projetos/glassdoor-reviews-analysis-nlp/golden_dataset/{VALIDATION_DATASET_NAME}"
    )
else:
    if running_kaggle:
        dataset = pd.read_csv(
            f"/kaggle/input/glassdoor-reviews-predicted/{VALIDATION_DATASET_NAME}"
        )
    else:
        dataset = pd.read_csv(f"./{VALIDATION_DATASET_NAME}")

In [17]:
dataset.head(2)

,review_id,company,employee_role,employee_detail,review_text,review_date,star_rating,sentiment
0,84941541,Sankhya Gestão de Negócios,Desenvolvedor,"Ex-funcionário(a), mais de um ano","Salário compatível, oportunidade de desenvolvi...",2 de mar. de 2024,5.0,1
1,84941541,Sankhya Gestão de Negócios,Desenvolvedor,"Ex-funcionário(a), mais de um ano",Não tenho o que reclamar da empresa,2 de mar. de 2024,5.0,-1

In [18]:
dataset.shape

(8212, 8)

In [19]:
dataset["sentiment"].value_counts()

sentiment
 1    4106
-1    4106
Name: count, dtype: int64

## Prediction over annotated dataset

In [21]:
tokenizer = BertTokenizer.from_pretrained(BERTIMBAU_PATH)

In [22]:
def convert_to_str(input_value):
    if isinstance(input_value, np.ndarray):
        input_str = " ".join(input_value)
    else:
        input_str = input_value

    return input_str

In [23]:
def predict_sentiment(review_text, model):
    outputs = []
    encoded_texts = tokenizer(
        review_text,
        max_length=TOKEN_MAX_LENGTH,
        add_special_tokens=True,
        return_token_type_ids=False,
        padding="max_length",
        truncation=True,
        return_attention_mask=True,
        return_tensors="pt",
    )

    input_ids = encoded_texts["input_ids"].to(device)
    attention_mask = encoded_texts["attention_mask"].to(device)

    with torch.no_grad():
        output = model(input_ids, attention_mask)
        probabilities = torch.nn.functional.softmax(output, dim=1)
        outputs.append(probabilities.cpu().numpy())

    return np.concatenate(outputs, axis=0)

### Predict reviews sentiment

In [24]:
total_iterations = len(dataset)
total_iterations

8212

In [ ]:
def predict(model, new_column):
    dataset[new_column] = pd.Series(dtype="int")

    for index, row in tqdm(
        dataset.iterrows(), total=total_iterations, desc="Processing"
    ):

        output_probabilities = predict_sentiment(
            review_text=row["review_text"], model=model
        )

        predicted_sentiment = np.argmax(output_probabilities)
        dataset.loc[index, new_column] = predicted_sentiment

        if index > 0 and index % 100 == 0:
            logging.info(f"Predicted rows: {index}/{total_iterations}")

            logging.info(

                f"Review Text: {row['review_text']};\nPredicted Sentiment: {predicted_sentiment}\n\n"
            )

    dataset[new_column] = dataset[new_column].astype(int)

#### Load models

In [26]:
class GlassdoorReviewsClassifier(nn.Module):
    def __init__(self, num_labels, classifier):
        super(GlassdoorReviewsClassifier, self).__init__()

        self.bert = BertModel.from_pretrained(BERTIMBAU_PATH)
        self.classifier = classifier

    def forward(self, input_ids, attention_mask):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        x = outputs["last_hidden_state"][:, 0, :]
        x = self.classifier(x)
        return x

In [32]:
model = GlassdoorReviewsClassifier(
    num_labels=N_CLASSES,
    classifier=nn.Sequential(
        nn.Linear(BERTIMBAU_HIDDEN_SIZE, 300),
        nn.ReLU(),
        nn.Linear(300, 100),
        nn.ReLU(),
        nn.Linear(100, 50),
        nn.ReLU(),
        nn.Linear(50, N_CLASSES),
    ),
).to(device)

In [28]:
if running_local:
    FINETUNED_MODEL_PATH = (
        "../train_model/bertimbau-glassdoor-reviews-oversampled-freezing-v1.bin"
    )

    if platform.system() == "Windows":
        BERTIMBAU_PATH = "C:\\bert-base-portuguese-cased"
    else:
        BERTIMBAU_PATH = "/home/stevillis/bert-base-portuguese-cased"

if running_colab:
    FINETUNED_MODEL_PATH = "/content/drive/MyDrive/UFMT/Gestão e Ciência de Dados/Disciplinas/14 - Seminário e Metodologia da Pesquisa/Projetos/glassdoor-reviews-analysis-nlp/train_model/bertimbau-glassdoor-reviews-oversampled-freezing-v1.bin"
    PREDICTIONS_PATH = "/content/drive/MyDrive/UFMT/Gestão e Ciência de Dados/Disciplinas/14 - Seminário e Metodologia da Pesquisa/Projetos/glassdoor-reviews-analysis-nlp/report"
if running_kaggle:
    FINETUNED_MODEL_PATH = "/kaggle/input/bertimbau-glassdoor-reviews-oversampled-freezing-v1.bin/pytorch/bertimbau-glassdoor-reviews-oversampled-freezing-v1.bin/1/bertimbau-glassdoor-reviews-oversampled-freezing-v1.bin"

In [29]:
FINETUNED_MODEL_PATH

'../train_model/bertimbau-glassdoor-reviews-oversampled-freezing-v1.bin'

In [33]:
model.load_state_dict(torch.load(FINETUNED_MODEL_PATH, map_location=device))
model.eval()

GlassdoorReviewsClassifier(
  (bert): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(29794, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0-11): 12 x BertLayer(
          (attention): BertAttention(
            (self): BertSdpaSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
          )
          (intermediate): BertIntermediate(
            (dense): Linear(in_features=768, out_features=3072, bias=True)
            (intermediate_act_fn): GELUActivation()
          )
          (output): BertOutput(
            (dense): Linear(in_features=3072, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
      )
    )
    (pooler): BertPooler(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (activation): Tanh()
    )
  )
  (classifier): Sequential(
    (0): Linear(in_features=768, out_features=300, bias=True)
    (1): ReLU()
    (2): Linear(in_features=300, out_features=100, bias=True)
    (3): ReLU()
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU()
    (6): Linear(in_features=50, out_features=3, bias=True)
  )
)

In [34]:
predict(
    model=model, new_column="predicted_sentiment_m1"
)  # predicted_sentiment_model_v1: m1 is the model with data augmentation and freezing bert layers

Processing:   0%|          | 0/8212 [00:00<?, ?it/s]c:\venvs\venv_sent_analysis\Lib\site-packages\transformers\models\bert\modeling_bert.py:440: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = torch.nn.functional.scaled_dot_product_attention(
Processing:   1%|          | 99/8212 [00:07<08:59, 15.03it/s] 2025-03-23 13:35:16,203 [INFO] Predicted rows: 100/8212
2025-03-23 13:35:16,203 [INFO] Review Text: Excelente empresa para se trabalhar, no quesito pessoas, benefícios, ambiente saudável;
Predicted Sentiment: 1


Processing:   2%|▏         | 199/8212 [00:13<09:00, 14.83it/s]2025-03-23 13:35:22,841 [INFO] Predicted rows: 200/8212
2025-03-23 13:35:22,841 [INFO] Review Text: Gestão bem definida, muitos benefícios, possibilidade de crescimento.;
Predicted Sentiment: 1


Processing:   4%|▎         | 299/8212 [00:20<08:43, 15.12it/s]2025-03-23 13:35:29,499 [INFO] Predicted rows: 300/8212
2025-03-23 13:35:29,502 [INFO] Review Text: Cultura, excelentes benefícios sem descontos em folha, investimento em aprendizado, pertencimento, COOs acessíveis, ambiente colaborativo, convenções produtivas e descontraídas, inclusão etc...;
Predicted Sentiment: 1


Processing:   5%|▍         | 399/8212 [00:27<08:42, 14.96it/s]2025-03-23 13:35:36,160 [INFO] Predicted rows: 400/8212
2025-03-23 13:35:36,175 [INFO] Review Text: Horário flexível, lideranças bem preparadas para condução de equipes, boa remuneração, ambiente bacana e diverso. Foco em desenvolvimento contínuo.;
Predicted Sentiment: 1


Processing:   6%|▌         | 499/8212 [00:34<08:34, 14.98it/s]2025-03-23 13:35:42,862 [INFO] Predicted rows: 500/8212
2025-03-23 13:35:42,862 [INFO] Review Text: **Excelência Profissional na TOTVS: Uma Experiência de Trabalho Inigualável**

Trabalhar na TOTVS é mais do que uma oportunidade profissional; é uma imersão em um ambiente de inovação, colaboração e crescimento contínuo. Ao longo do meu tempo nesta empresa, pude vivenciar em primeira mão os valores que a tornam única e a consolidam como referência no setor.

A cultura corporativa da TOTVS é um dos principais motivos pelos quais a recomendo entusiasticamente a colegas e amigos. A empresa não apenas valoriza a diversidade, mas a celebra como um pilar fundamental para o sucesso. Aqui, cada voz é ouvida, cada perspectiva é respeitada e as diferenças são encaradas como oportunidades para aprender e crescer juntos.

A TOTVS investe consistentemente no desenvolvimento profissional de seus colaboradores. Seja por meio de treinamentos específicos, programas de capacitação ou mentorias, a empresa demonstra um compromisso genuíno em impulsionar a carreira de seus funcionários. A atmosfera de aprendizado constante é palpável e cria um ambiente propício para o surgimento de profissionais altamente qualificados e motivados.

Além disso, a TOTVS está na vanguarda da inovação tecnológica, oferecendo projetos desafiadores que estimulam a criatividade e o pensamento crítico. Trabalhar em uma empresa que abraça a transformação digital e se mantém na vanguarda das tendências do mercado proporciona uma sensação de relevância e impacto profundo em nossas atividades diárias.

Outro ponto que destaco é a preocupação da TOTVS com o equilíbrio entre vida profissional e pessoal. A empresa compreende a importância de uma jornada de trabalho saudável e promove políticas que incentivam o bem-estar de seus colaboradores, criando um ambiente onde é possível prosperar tanto profissional quanto pessoalmente.

Em resumo, a TOTVS é mais do que uma empresa; é uma comunidade comprometida com o sucesso de seus colaboradores. Recomendo-a a todos que buscam não apenas um emprego, mas uma carreira gratificante, repleta de desafios estimulantes, aprendizado contínuo e um ambiente de trabalho acolhedor. Aqui, na TOTVS, construí não apenas uma carreira, mas também uma jornada de realizações profissionais e pessoais que não trocaria por nada.;
Predicted Sentiment: 1


Processing:   7%|▋         | 599/8212 [00:40<08:28, 14.97it/s]2025-03-23 13:35:49,538 [INFO] Predicted rows: 600/8212
2025-03-23 13:35:49,555 [INFO] Review Text: Cultura da empresa, benefícios e clima;
Predicted Sentiment: 1


Processing:   9%|▊         | 699/8212 [00:47<08:14, 15.20it/s]2025-03-23 13:35:56,263 [INFO] Predicted rows: 700/8212
2025-03-23 13:35:56,263 [INFO] Review Text: Totvs possui um ambiente colaborativo entre os membros da equipe, o que faz com que o aprendizado e a jornada se torne mais leve e de fácil assimilação.;
Predicted Sentiment: 1


Processing:  10%|▉         | 799/8212 [00:54<08:10, 15.11it/s]2025-03-23 13:36:02,972 [INFO] Predicted rows: 800/8212
2025-03-23 13:36:02,976 [INFO] Review Text: Flexibilidade, autonomia e possibilidade de conciliar vida pessoal com profissional;
Predicted Sentiment: 1


Processing:  11%|█         | 899/8212 [01:00<08:14, 14.78it/s]2025-03-23 13:36:09,674 [INFO] Predicted rows: 900/8212
2025-03-23 13:36:09,674 [INFO] Review Text: Salário
Benefícios
Ambiente
Modelo de trabalho home office;
Predicted Sentiment: 1


Processing:  12%|█▏        | 999/8212 [01:07<08:08, 14.78it/s]2025-03-23 13:36:16,380 [INFO] Predicted rows: 1000/8212
2025-03-23 13:36:16,380 [INFO] Review Text: Empresa ótima pra trabalhar. Pessoas companheiras;
Predicted Sentiment: 1


Processing:  13%|█▎        | 1099/8212 [01:14<07:53, 15.01it/s]2025-03-23 13:36:23,115 [INFO] Predicted rows: 1100/8212
2025-03-23 13:36:23,117 [INFO] Review Text: Excelente ambiente e estrutura. Profissionais comprometidos e respeitosos.;
Predicted Sentiment: 1


Processing:  15%|█▍        | 1199/8212 [01:20<07:56, 14.71it/s]2025-03-23 13:36:29,840 [INFO] Predicted rows: 1200/8212
2025-03-23 13:36:29,842 [INFO] Review Text: Pacote amplo de benefícios e sempre com novidades;
Predicted Sentiment: 1


Processing:  16%|█▌        | 1299/8212 [01:27<07:39, 15.04it/s]2025-03-23 13:36:36,563 [INFO] Predicted rows: 1300/8212
2025-03-23 13:36:36,578 [INFO] Review Text: Home Office, ambiente de trabalho, Cooperação, Crescimento;
Predicted Sentiment: 1


Processing:  17%|█▋        | 1399/8212 [01:34<07:40, 14.80it/s]2025-03-23 13:36:43,308 [INFO] Predicted rows: 1400/8212
2025-03-23 13:36:43,308 [INFO] Review Text: Ambiente agradável para trabalhar, jornada de 40 horas semanais, intervalo de almoço de 90 minutos.;
Predicted Sentiment: 1


Processing:  18%|█▊        | 1499/8212 [01:41<07:23, 15.12it/s]2025-03-23 13:36:50,008 [INFO] Predicted rows: 1500/8212
2025-03-23 13:36:50,025 [INFO] Review Text: TOTVS tem um clima leve, inovador, focada em resultados, respeita e valoriza a diversidade, é uma empresa sólida e humana. Os TOTVERS são extremamente parceiros e colaborativos, sou apaixonada por essa empresa.;
Predicted Sentiment: 1


Processing:  19%|█▉        | 1599/8212 [01:47<07:21, 14.99it/s]2025-03-23 13:36:56,754 [INFO] Predicted rows: 1600/8212
2025-03-23 13:36:56,754 [INFO] Review Text: Uma empresa gigante, acolhedora, desafiadora. Você tem acesso constante a muitos treinamentos e capacitações.;
Predicted Sentiment: 1


Processing:  21%|██        | 1699/8212 [01:54<07:22, 14.74it/s]2025-03-23 13:37:03,524 [INFO] Predicted rows: 1700/8212
2025-03-23 13:37:03,527 [INFO] Review Text: Como eu preciso fazer as demonstrações dos produtos, a univesidade TOTVS é muito importante para conhecer e repassar para os clientes e prospets, as funcionalidades que vão ajudar os nossos clientes.;
Predicted Sentiment: 0


Processing:  22%|██▏       | 1799/8212 [02:01<07:06, 15.04it/s]2025-03-23 13:37:10,250 [INFO] Predicted rows: 1800/8212
2025-03-23 13:37:10,266 [INFO] Review Text: Empresa com a melhor comunicação interna que eu já trabalhei. Plano de carreira e RH estruturado. Universidade corporativa online e muito boa. Valores humanos muito presentes em todas as camadas.;
Predicted Sentiment: 1


Processing:  23%|██▎       | 1899/8212 [02:08<07:08, 14.72it/s]2025-03-23 13:37:17,022 [INFO] Predicted rows: 1900/8212
2025-03-23 13:37:17,031 [INFO] Review Text: bem estruturada, comunicação 360, flexibilidade de horario;
Predicted Sentiment: 1


Processing:  24%|██▍       | 1999/8212 [02:14<07:03, 14.68it/s]2025-03-23 13:37:23,792 [INFO] Predicted rows: 2000/8212
2025-03-23 13:37:23,795 [INFO] Review Text: Ótimo ambiente, grande flexibilidade, oportunidade em crescimento.;
Predicted Sentiment: 1


Processing:  26%|██▌       | 2099/8212 [02:21<06:51, 14.87it/s]2025-03-23 13:37:30,541 [INFO] Predicted rows: 2100/8212
2025-03-23 13:37:30,541 [INFO] Review Text: Predio moderno e bonito, com toda infra para se trabalhar.;
Predicted Sentiment: 1


Processing:  27%|██▋       | 2199/8212 [02:28<06:40, 15.00it/s]2025-03-23 13:37:37,241 [INFO] Predicted rows: 2200/8212
2025-03-23 13:37:37,241 [INFO] Review Text: Novas ideias para tecnologia da Informação;
Predicted Sentiment: 1


Processing:  28%|██▊       | 2299/8212 [02:35<06:33, 15.01it/s]2025-03-23 13:37:43,972 [INFO] Predicted rows: 2300/8212
2025-03-23 13:37:43,989 [INFO] Review Text: Localização, ambiente, de fato possuem boa gente.;
Predicted Sentiment: 1


Processing:  29%|██▉       | 2399/8212 [02:41<06:24, 15.10it/s]2025-03-23 13:37:50,686 [INFO] Predicted rows: 2400/8212
2025-03-23 13:37:50,686 [INFO] Review Text: Empresa de nome, serve pra dar peso ao currículo. No geral, bom ambiente de trabalho.;
Predicted Sentiment: 1


Processing:  30%|███       | 2499/8212 [02:48<06:20, 15.00it/s]2025-03-23 13:37:57,400 [INFO] Predicted rows: 2500/8212
2025-03-23 13:37:57,400 [INFO] Review Text: Empresa maravilhosa de trabalhar. Plano de carreira;
Predicted Sentiment: 1


Processing:  32%|███▏      | 2599/8212 [02:55<06:18, 14.85it/s]2025-03-23 13:38:04,099 [INFO] Predicted rows: 2600/8212
2025-03-23 13:38:04,099 [INFO] Review Text: Uma empresa com ambiente harmonioso.;
Predicted Sentiment: 1


Processing:  33%|███▎      | 2699/8212 [03:01<06:13, 14.76it/s]2025-03-23 13:38:10,840 [INFO] Predicted rows: 2700/8212
2025-03-23 13:38:10,840 [INFO] Review Text: não existe nada de bom lá;
Predicted Sentiment: 2


Processing:  34%|███▍      | 2799/8212 [03:08<06:00, 15.02it/s]2025-03-23 13:38:17,576 [INFO] Predicted rows: 2800/8212
2025-03-23 13:38:17,576 [INFO] Review Text: - Estabilidade

- Salário compatível com o mercado

- Exposição profissional;
Predicted Sentiment: 1


Processing:  35%|███▌      | 2899/8212 [03:15<05:55, 14.95it/s]2025-03-23 13:38:24,291 [INFO] Predicted rows: 2900/8212
2025-03-23 13:38:24,291 [INFO] Review Text: Muito bom de trabalhar na empresa;
Predicted Sentiment: 1


Processing:  37%|███▋      | 2999/8212 [03:22<05:47, 15.01it/s]2025-03-23 13:38:31,009 [INFO] Predicted rows: 3000/8212
2025-03-23 13:38:31,009 [INFO] Review Text: Otima empresa e infraestrutura para se trabalhar.;
Predicted Sentiment: 1


Processing:  38%|███▊      | 3099/8212 [03:28<05:42, 14.92it/s]2025-03-23 13:38:37,728 [INFO] Predicted rows: 3100/8212
2025-03-23 13:38:37,745 [INFO] Review Text: Alimentação ou Refeição, Transporte, Plano de Saúde, Previdencia Privada.;
Predicted Sentiment: 1


Processing:  39%|███▉      | 3199/8212 [03:35<05:35, 14.94it/s]2025-03-23 13:38:44,475 [INFO] Predicted rows: 3200/8212
2025-03-23 13:38:44,475 [INFO] Review Text: Uma boa empresa para trabalhar.;
Predicted Sentiment: 1


Processing:  40%|████      | 3299/8212 [03:42<05:28, 14.94it/s]2025-03-23 13:38:51,170 [INFO] Predicted rows: 3300/8212
2025-03-23 13:38:51,170 [INFO] Review Text: Empresa com bons beneficios (poderia ser melhor) mas no geral é ok;
Predicted Sentiment: 1


Processing:  41%|████▏     | 3399/8212 [03:49<05:21, 14.98it/s]2025-03-23 13:38:57,885 [INFO] Predicted rows: 3400/8212
2025-03-23 13:38:57,886 [INFO] Review Text: benefícios, salario, gestão, flexibilidade de horário;
Predicted Sentiment: 1


Processing:  43%|████▎     | 3499/8212 [03:55<05:13, 15.03it/s]2025-03-23 13:39:04,605 [INFO] Predicted rows: 3500/8212
2025-03-23 13:39:04,605 [INFO] Review Text: Benefícios (Gympass, convênio médico e odontológico e etc)
Ambiente colaborativo
Equipe legal
Coordenação boa;
Predicted Sentiment: 1


Processing:  44%|████▍     | 3599/8212 [04:02<05:08, 14.93it/s]2025-03-23 13:39:11,308 [INFO] Predicted rows: 3600/8212
2025-03-23 13:39:11,308 [INFO] Review Text: Estabilidade, Benefícios, Amizade, Salário e Liberdade;
Predicted Sentiment: 1


Processing:  45%|████▌     | 3699/8212 [04:09<04:58, 15.10it/s]2025-03-23 13:39:18,010 [INFO] Predicted rows: 3700/8212
2025-03-23 13:39:18,010 [INFO] Review Text: Bom ambiente de trabalho

Interesse em manter o funcionário;
Predicted Sentiment: 1


Processing:  46%|████▋     | 3799/8212 [04:15<04:53, 15.04it/s]2025-03-23 13:39:24,729 [INFO] Predicted rows: 3800/8212
2025-03-23 13:39:24,729 [INFO] Review Text: Oportunidade de desenvolvimento profissional para quem está desempregado;
Predicted Sentiment: 1


Processing:  47%|████▋     | 3899/8212 [04:22<04:47, 14.98it/s]2025-03-23 13:39:31,448 [INFO] Predicted rows: 3900/8212
2025-03-23 13:39:31,448 [INFO] Review Text: Unimed

Gympass

Plano Odontológico

Grande empresa, oportunidades internas;
Predicted Sentiment: 1


Processing:  49%|████▊     | 3999/8212 [04:29<04:40, 15.01it/s]2025-03-23 13:39:38,149 [INFO] Predicted rows: 4000/8212
2025-03-23 13:39:38,151 [INFO] Review Text: *Ambiente favorável

*Salário não é o mais alto do mercado, mas é compatível.

*Ótimos benefícios.

*Empresa investe no funcionário tecnicamente com cursos, palestras, webinares, etc.

*Sistemas com anos no mercado, bem construídos e padronizados.

*Uma empresa consolidada no mercado, e que você pode ficar a vida toda.;
Predicted Sentiment: 1


Processing:  50%|████▉     | 4099/8212 [04:36<04:43, 14.53it/s]2025-03-23 13:39:44,937 [INFO] Predicted rows: 4100/8212
2025-03-23 13:39:44,939 [INFO] Review Text: Bom ambiente de trabalho, perfeitas instalações, se percebe que a empresa tenta se inovar sempre e é participava na comunidade de TI permitindo que eventos sejam realizados nas suas instalações.;
Predicted Sentiment: 1


Processing:  51%|█████     | 4199/8212 [04:42<04:32, 14.75it/s]2025-03-23 13:39:51,691 [INFO] Predicted rows: 4200/8212
2025-03-23 13:39:51,691 [INFO] Review Text: O fato da empresa ter por premissa reinventar-se sempre, abre espaço para que muitos possam contribuir de alguma maneira, independente de nível hierárquico.

Minhas experiências e conhecimentos tem valor aqui dentro e isso gera muita satisfação! Com isso vejo muito espaço para desenvolvimento e crescimento na TOTVS.

Além disso, fatores como: a flexibilidade de jornada, opção de home office, flexibilização do dress code, entre outros aspectos deixam a vida profissional mais leve...;
Predicted Sentiment: 1


Processing:  52%|█████▏    | 4299/8212 [04:49<04:29, 14.51it/s]2025-03-23 13:39:58,459 [INFO] Predicted rows: 4300/8212
2025-03-23 13:39:58,463 [INFO] Review Text: Oportunidades de aprendizado em diversas áreas; Contato com profissionais de alta performance; Incentivo à evolução diária; Oportunidade de acesso à diversas culturas diferentes de nossos clientes;;
Predicted Sentiment: 1


Processing:  54%|█████▎    | 4399/8212 [04:56<04:13, 15.03it/s]2025-03-23 13:40:05,200 [INFO] Predicted rows: 4400/8212
2025-03-23 13:40:05,200 [INFO] Review Text: Já não sei falar os pontos positivos. Estou a 8 anos na empresa e por ser uma multi nacional não vejo a devida valorização dos funcionários.;
Predicted Sentiment: 0


Processing:  55%|█████▍    | 4499/8212 [05:03<04:06, 15.06it/s]2025-03-23 13:40:11,934 [INFO] Predicted rows: 4500/8212
2025-03-23 13:40:11,934 [INFO] Review Text: Empresa inovadora, que pensa muito no futuro, tem uma história sensacional. A infraestrutura da matriz é excelente. Tem muito profissional bom na empresa.;
Predicted Sentiment: 1


Processing:  56%|█████▌    | 4599/8212 [05:09<04:04, 14.79it/s]2025-03-23 13:40:18,650 [INFO] Predicted rows: 4600/8212
2025-03-23 13:40:18,650 [INFO] Review Text: Ambiente agradável de se conviver, com muitas pessoas alegres, liberdade de desenvolver o seu trabalho, bastante benefícios e desafios ao longo do dia, além de contar com horários de trabalho flexíveis,;
Predicted Sentiment: 1


Processing:  57%|█████▋    | 4699/8212 [05:16<03:54, 14.97it/s]2025-03-23 13:40:25,434 [INFO] Predicted rows: 4700/8212
2025-03-23 13:40:25,437 [INFO] Review Text: Ótimo ambiente de se trabalhar, colaboradores de bem, ótimo para aprendizado e novas oportunidades dentro da própria empresa e um plano de carreira.;
Predicted Sentiment: 1


Processing:  58%|█████▊    | 4799/8212 [05:23<03:48, 14.93it/s]2025-03-23 13:40:32,188 [INFO] Predicted rows: 4800/8212
2025-03-23 13:40:32,188 [INFO] Review Text: Ambiente bonito, organizado, descontraído, com video game, mesa de sinuca, copa, sala de descanso, fretado até o metrô, treinamentos, benefícios como VR,VT,PLR,Seguro de vida, auxilio a previdência privada.;
Predicted Sentiment: 1


Processing:  60%|█████▉    | 4899/8212 [05:30<03:40, 15.02it/s]2025-03-23 13:40:38,908 [INFO] Predicted rows: 4900/8212
2025-03-23 13:40:38,908 [INFO] Review Text: A empresa investe muito na qualificação dos profissionais e tem um ambiente de trabalho muito agradável. Tem um sistema de bonificação que estimula o funcionário a buscar sempre mais.;
Predicted Sentiment: 1


Processing:  61%|██████    | 4999/8212 [05:36<03:32, 15.09it/s]2025-03-23 13:40:45,660 [INFO] Predicted rows: 5000/8212
2025-03-23 13:40:45,660 [INFO] Review Text: É uma empresa que todos são motivados, há reconhecimentos individuais e o salário é muito bom. Há plano de carreira e a comunicação com a alta gestão é simples e acontece.;
Predicted Sentiment: 1


Processing:  62%|██████▏   | 5099/8212 [05:43<03:26, 15.06it/s]2025-03-23 13:40:52,432 [INFO] Predicted rows: 5100/8212
2025-03-23 13:40:52,434 [INFO] Review Text: Um ótimo prédio, bem localizado (fora da zona sul onde maioria das empresas estão). A empresa tem bastante benefícios e é bastante confiável.;
Predicted Sentiment: 1


Processing:  63%|██████▎   | 5199/8212 [05:50<03:24, 14.75it/s]2025-03-23 13:40:59,179 [INFO] Predicted rows: 5200/8212
2025-03-23 13:40:59,195 [INFO] Review Text: Ambiente de trabalho e espaço físico são muito bons, a tecnologia desenvolvida pela empresa é uma das maiores do pais e o ERP muito utilizado no mercado por diversas empresas;
Predicted Sentiment: 1


Processing:  65%|██████▍   | 5299/8212 [05:57<03:16, 14.82it/s]2025-03-23 13:41:05,934 [INFO] Predicted rows: 5300/8212
2025-03-23 13:41:05,934 [INFO] Review Text: O ambiente de trabalho é agradável, sem muita pressão ou cobrança por parte da liderança. A maioria das pessoas está sempre disposta a ajudar a resolver as situações enfrentadas no dia-a-dia.;
Predicted Sentiment: 1


Processing:  66%|██████▌   | 5399/8212 [06:03<03:14, 14.49it/s]2025-03-23 13:41:12,654 [INFO] Predicted rows: 5400/8212
2025-03-23 13:41:12,654 [INFO] Review Text: - Clima extremamente agradável - Pessoas carismáticas - Opiniões são escutadas pelos gestores - Local de fácil acesso - Empresa Inovadora e em constante evolução;
Predicted Sentiment: 1


Processing:  67%|██████▋   | 5499/8212 [06:10<03:00, 15.03it/s]2025-03-23 13:41:19,356 [INFO] Predicted rows: 5500/8212
2025-03-23 13:41:19,356 [INFO] Review Text: Salário, aprendizado, ambiente, benefícios, qualidade de vida, preocupação com o desenvolvimento das pessoas. Recursos Humanos funciona muito bem e tem profissionais competentes;
Predicted Sentiment: 1


Processing:  68%|██████▊   | 5599/8212 [06:17<02:52, 15.12it/s]2025-03-23 13:41:26,065 [INFO] Predicted rows: 5600/8212
2025-03-23 13:41:26,068 [INFO] Review Text: Ambiente de trabalho interno, repasse de conhecimento dos colegas de trabalho;
Predicted Sentiment: 1


Processing:  69%|██████▉   | 5699/8212 [06:23<02:51, 14.69it/s]2025-03-23 13:41:32,795 [INFO] Predicted rows: 5700/8212
2025-03-23 13:41:32,795 [INFO] Review Text: Permite protagonismo no ambiente de trabalho, autonomia, a gente aprende muito na TOTVS.;
Predicted Sentiment: 1



In [35]:
dataset.head(3)

,review_id,company,employee_role,employee_detail,review_text,review_date,star_rating,sentiment,predicted_sentiment_m1
0,84941541,Sankhya Gestão de Negócios,Desenvolvedor,"Ex-funcionário(a), mais de um ano","Salário compatível, oportunidade de desenvolvi...",2 de mar. de 2024,5.0,1,1
1,84941541,Sankhya Gestão de Negócios,Desenvolvedor,"Ex-funcionário(a), mais de um ano",Não tenho o que reclamar da empresa,2 de mar. de 2024,5.0,-1,0
2,85370906,Sankhya Gestão de Negócios,Associate Product Owner Sênior,"Funcionário(a) atual, mais de 3 anos",Plano médico 100% gratuito para colaborador;\n...,15 de mar. de 2024,3.0,1,1

In [36]:
dataset["predicted_sentiment_m1"].value_counts()

predicted_sentiment_m1
1    4305
2    3310
0     597
Name: count, dtype: int64

#### Saving predicted validation dataset

In [38]:
dataset.to_csv(
    f"{PREDICTIONS_PATH}/{VALIDATION_DATASET_NAME}",
    index=False,
)

In [39]:
if running_kaggle:
    %cd /kaggle/working
    from IPython.display import FileLink
    FileLink(f"/kaggle/working/{VALIDATION_DATASET_NAME}")

#### Saving predicted golden dataset

In [ ]:
n_samples = 200

In [41]:
neutral_reviews = dataset[dataset["predicted_sentiment_m1"] == 0].sample(
    n=n_samples, random_state=RANDOM_SEED
)

In [42]:
positive_reviews = dataset[dataset["predicted_sentiment_m1"] == 1].sample(
    n=n_samples, random_state=RANDOM_SEED
)

In [43]:
negative_reviews = dataset[dataset["predicted_sentiment_m1"] == 2].sample(
    n=n_samples, random_state=RANDOM_SEED
)

In [44]:
golden_reviews_df = pd.concat([neutral_reviews, positive_reviews, negative_reviews])

In [47]:
golden_reviews_df.head(2)

,review_id,company,employee_role,employee_detail,review_text,review_date,star_rating,sentiment,predicted_sentiment_m1
3239,59712014,TOTVS,Consultor Comercial,"Funcionário(a) atual, mais de 3 anos",No momento ainda não identifiquei.,15 de fev. de 2022,5.0,-1,0
7461,43405389,TOTVS,Business Analyst,Funcionário(a) atual,Não vejo contras no momento,3 de mar. de 2021,4.0,-1,0

In [49]:
golden_reviews_df["predicted_sentiment_m1"].value_counts()

predicted_sentiment_m1
0    200
1    200
2    200
Name: count, dtype: int64

In [45]:
golden_reviews_df.to_csv(
    f"{PREDICTIONS_PATH}/{GOLDEN_DATASET_NAME}",
    index=False,
)

In [46]:
if running_kaggle:
    %cd /kaggle/working
    from IPython.display import FileLink
    FileLink(f"/kaggle/working/{GOLDEN_DATASET_NAME}")